package handlers

import (
	_ "github.com/alessio-palumbo/frankie-financial-test/docs" // Import docs generated by Swag CLI.
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"github.com/alessio-palumbo/frankie-financial-test/pkg/cache"
)

// Handler is a handler with an internal cache
type Handler struct {
	SessionCache *cache.SessionCache
}

// SetupRouter registers the listed endpoints and the returns a router.
func SetupRouter() *gin.Engine {
	r := gin.Default()

	// url := ginSwagger.URL("http://localhost:8080/swagger/doc.json") // The url pointing to API definition
	// r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))

	// Initialise the handler's cache to use to validate checkSessionKeys in this session.
	handler := Handler{cache.New()}

	r.POST("/isgood", handler.DeviceCheck)

	// Serve swagger docs
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return r
}
